// eslint-disable-next-line import/no-anonymous-default-export
export default {
    "login": "claudeshyaka",
    "id": 34720859,
    "node_id": "MDQ6VXNlcjM0NzIwODU5",
    "avatar_url": "https://avatars.githubusercontent.com/u/34720859?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/claudeshyaka",
    "html_url": "https://github.com/claudeshyaka",
    "followers_url": "https://api.github.com/users/claudeshyaka/followers",
    "following_url": "https://api.github.com/users/claudeshyaka/following{/other_user}",
    "gists_url": "https://api.github.com/users/claudeshyaka/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/claudeshyaka/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/claudeshyaka/subscriptions",
    "organizations_url": "https://api.github.com/users/claudeshyaka/orgs",
    "repos_url": "https://api.github.com/users/claudeshyaka/repos",
    "events_url": "https://api.github.com/users/claudeshyaka/events{/privacy}",
    "received_events_url": "https://api.github.com/users/claudeshyaka/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Claude E. Shyaka",
    "company": null,
    "blog": "",
    "location": "Charlotte, NC",
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": null,
    "public_repos": 13,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2017-12-20T18:44:00Z",
    "updated_at": "2022-05-26T18:32:25Z"
};